{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- if eq .Values.scope.type "namespace" }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
  name: {{ include "pipeline-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pipeline-operator.name" . }}
    app.kubernetes.io/part-of: algo.run
    helm.sh/chart: {{ include "pipeline-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - events
    - configmaps
    - secrets
    verbs:
    - get
    - list
    - watch
    - create
    - patch
    - update
    - delete
  - apiGroups:
    - algo.run
    resources:
    - '*'
    verbs:
    - get
    - list
    - watch
    - create
    - patch
    - update
    - delete
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
    - deployments/finalizers
    verbs:
    - get
    - list
    - watch
    - create
    - patch
    - update
    - delete
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    verbs:
    - get
    - create
  - apiGroups:
    - kafka.strimzi.io
    resources:
    - kafkatopics
    - kafkausers
    - kafkaconnects
    - kafkaconnectors
    verbs:
    - get
    - list
    - watch
    - create
    - patch
    - update
    - delete

  {{- if .Values.rbac.podSecurityPolicies }}
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames:
      {{- toYaml .Values.rbac.podSecurityPolicies | nindent 6 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- if eq .Values.scope.type "namespace" }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
metadata:
  name: {{ include "pipeline-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pipeline-operator.name" . }}
    app.kubernetes.io/part-of: algo.run
    helm.sh/chart: {{ include "pipeline-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if eq .Values.scope.type "namespace" }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ include "pipeline-operator.fullname" . }}
subjects:
  - name: {{ include "pipeline-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
{{- end -}}