{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pipeline-operator.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "pipeline-operator.name" . }}
    app.kubernetes.io/part-of: algo.run
    app.kubernetes.io/component: pipeline-operator
    helm.sh/chart: {{ include "pipeline-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "pipeline-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
