{{- if .Values.metrics.endpointServiceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ include "pipeline-operator.name" . }}-endpoint-sm"
  {{- if .Values.metrics.serviceMonitorNamespace }}
  namespace: {{ .Values.metrics.serviceMonitorNamespace }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "pipeline-operator.name" . }}
    app.kubernetes.io/part-of: algo.run
    app.kubernetes.io/component: pipeline-operator
    helm.sh/chart: {{ include "pipeline-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.metrics.endpointServiceMonitor.additionalLabels }}
{{ toYaml .Values.metrics.endpointServiceMonitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  endpoints:
  - port: metrics
    interval: {{ .Values.metrics.endpointServiceMonitor.interval }}
    {{- if .Values.metrics.endpointServiceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.metrics.endpointServiceMonitor.scrapeTimeout }}
    {{- end }}
    honorLabels: {{ .Values.metrics.endpointServiceMonitor.honorLabels }}
    {{- if .Values.metrics.endpointServiceMonitor.relabellings }}
    metricRelabelings:
{{ toYaml .Values.metrics.endpointServiceMonitor.relabellings | indent 6 }}
    {{- end }}
  {{- if eq .Values.scope.type "namespace" }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- else }}
  namespaceSelector:
    any: true
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/part-of: algo.run
      app.kubernetes.io/component: endpoint
{{- end }}
