{{- if .Values.metrics.pipelineOperatorServiceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ include "pipeline-operator.name" . }}-sm"
  {{- if .Values.metrics.serviceMonitorNamespace }}
  namespace: {{ .Values.metrics.serviceMonitorNamespace }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "pipeline-operator.name" . }}
    app.kubernetes.io/part-of: algo.run
    app.kubernetes.io/component: pipeline-operator
    helm.sh/chart: {{ include "pipeline-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.metrics.pipelineOperatorServiceMonitor.additionalLabels }}
{{ toYaml .Values.metrics.pipelineOperatorServiceMonitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  endpoints:
  - port: metrics
    interval: {{ .Values.metrics.pipelineOperatorServiceMonitor.interval }}
    {{- if .Values.metrics.pipelineOperatorServiceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.metrics.pipelineOperatorServiceMonitor.scrapeTimeout }}
    {{- end }}
    honorLabels: {{ .Values.metrics.pipelineOperatorServiceMonitor.honorLabels }}
    {{- if .Values.metrics.pipelineOperatorServiceMonitor.relabellings }}
    metricRelabelings:
{{ toYaml .Values.metrics.pipelineOperatorServiceMonitor.relabellings | indent 6 }}
    {{- end }}
  - port: op-metrics
    interval: {{ .Values.metrics.pipelineOperatorServiceMonitor.interval }}
    {{- if .Values.metrics.pipelineOperatorServiceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.metrics.pipelineOperatorServiceMonitor.scrapeTimeout }}
    {{- end }}
    honorLabels: {{ .Values.metrics.pipelineOperatorServiceMonitor.honorLabels }}
    {{- if .Values.metrics.pipelineOperatorServiceMonitor.relabellings }}
    metricRelabelings:
{{ toYaml .Values.metrics.pipelineOperatorServiceMonitor.relabellings | indent 6 }}
    {{- end }}
  {{- if eq .Values.scope.type "namespace" }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- else }}
  namespaceSelector:
    any: true
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "pipeline-operator.name" . }}
      release: "{{ .Release.Name }}"
{{- end }}
